services:
  postgres:
    image: postgres:17.4
    container_name: lgcm-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5434:5432"
    networks:
      - lgcm-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: lgcm-server
    image: lgcm-server:latest
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - NODE_ENV=development
      - PINO_LOG_LEVEL=debug
      - PORT=3002
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - lgcm-network
    command: >
      sh -c "
        npx drizzle-kit generate &&
        npx drizzle-kit migrate
        node ./dist/main.js
      "

  client:
    container_name: lgcm-client
    image: lgcm-client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:3002
    environment:
      - VITE_API_URL=http://localhost:3002
    ports:
      - 4173:4173
    networks:
      - lgcm-network
  
volumes:
  postgres-data:
  influxdb_data:
  grafana_data:
  grafana_logs:
networks:
  lgcm-network:
    name: lgcm-network