services:
  influxdb:
    container_name: lgcm-influxdb
    image: influxdb:1.8.10
    networks:
      - k6
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    volumes:
    - influxdb_data:/var/lib/influxdb

  grafana:
    container_name: lgcm-grafana
    image: grafana/grafana:10.2.2
    networks:
      - k6
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana

  k6:
    container_name: lgcm-k6 
    image: grafana/k6:latest
    networks:
      - k6
      - lgcm-network
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./scripts:/scripts

  alloy:
    image: grafana/alloy:latest
    container_name: lgcm-alloy
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    ports:
      - "12345:12345"
    volumes:
      - ./alloy.config:/etc/alloy/config.alloy
      - alloy_data:/var/lib/alloy/data
    networks:
      - k6

  prometheus:
    image: docker.io/prom/prometheus:latest
    ports:
      - "9090:9090"
    command: "--config.file=/etc/prometheus/prometheus.yaml --web.enable-remote-write-receiver"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus_data:/prometheus
    networks:
      - k6

volumes:
  influxdb_data:
  grafana_data:
  grafana_logs:
  alloy_data:
  prometheus_data:
networks:
  k6:
    name: k6
  lgcm-network:
    name: lgcm-network
    external: true